# Generated by Django 5.1.5 on 2025-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_subscriptionplan_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'permissions': [('create_room_reservation', 'Can create room reservation'), ('create_accounts', 'Can create accounts'), ('read_accounts', 'Can read accounts'), ('update_accounts', 'Can update accounts'), ('delete_accounts', 'Can delete accounts'), ('create_purchase', 'Can create purchase'), ('update_purchase', 'Can update purchase'), ('delete_purchase', 'Can delete purchase'), ('read_purchase', 'Can read purchase'), ('create_units', 'Can create units'), ('update_units', 'Can update units'), ('delete_units', 'Can delete units'), ('read_units', 'Can read units')],
            },
        ),
    ]
