# Generated by Django 5.1.5 on 2025-04-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_permissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Permission',
        ),
    ]
