# Generated by Django 5.1.5 on 2025-04-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_permissions_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='room_name',
            new_name='role',
        ),
    ]
